# Generated by Django 4.0.4 on 2022-05-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='role',
            field=models.CharField(choices=[('new', 'Новые'), ('exsept', 'Принятые'), ('cancelled', 'Отменные')], default='new', max_length=254, verbose_name='Статус'),
        ),
    ]
