# Generated by Django 4.0.4 on 2022-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_orders_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
    ]
