# Generated by Django 4.0.4 on 2022-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_basket_count_remove_goods_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
